#                     __                       
#    ____ ___  ____ _/ /___  ______ ____  ____ 
#   / __ `__ \/ __ `/ __/ / / / __ `/ _ \/ __ \
#  / / / / / / /_/ / /_/ /_/ / /_/ /  __/ / / /
# /_/ /_/ /_/\__,_/\__/\__,_/\__, /\___/_/ /_/ 
#                           /____/             

[config.wallpaper]
command = "swww"
arguments = ["img", "--transition-type", "none"]
set = true

[templates.hyprland]
input_path = "./templates/hyprland-colors.conf"
output_path = "~/.dotfiles/.config/hypr/conf/colors.conf"

[templates.kitty]
input_path = "./templates/kitty-colors.conf"
output_path = "~/.dotfiles/.config/kitty/colors.conf"

[templates.rofi]
input_path = "./templates/rofi-colors.rasi"
output_path = "~/.dotfiles/.config/rofi/colors.rasi"

[templates.waybar]
input_path = "./templates/colors.css"
output_path = "~/.dotfiles/.config/waybar/colors.css"

[templates.gtk3]
input_path = "./templates/gtk-colors.css"
output_path = "~/.dotfiles/.config/gtk-3.0/colors.css"

[templates.gtk4]
input_path = "./templates/gtk-colors.css"
output_path = "~/.dotfiles/.config/gtk-4.0/colors.css"

[templates.dunst]
input_path = "./templates/dunstrc-colors"
output_path = "~/.dotfiles/.config/dunst/dunstrc"

[templates.qt6ct]
input_path = "./templates/qtct-colors.conf"
output_path = "~/.dotfiles/.config/qt6ct/colors/matugen.conf"

[templates.qt5ct]
input_path = "./templates/qtct-colors.conf"
output_path = "~/.dotfiles/.config/qt5ct/colors/matugen.conf"

[templates.btop]
input_path = "./templates/btop.theme"
output_path = "~/.dotfiles/.config/btop/themes/matugen.theme"

[templates.rmpc]
input_path = "./templates/rmpc-theme.ron"
output_path = "~/.dotfiles/.config/rmpc/theme.ron"

[templates.vesktop]
input_path = "./templates/discord-theme.css"
output_path = "~/.config/Vencord/themes/midnight-discord.css"

[templates.vscode]
input_path = "./templates/vscode-theme.jsonc"
output_path = "~/.config/Code/User/settings.json"
